productmanager/product/routes.py
from productmanager import db
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required
from productmanager.product.forms import ProductRegisterForm
from productmanager.product.models import Product

product_api = Blueprint('product_api', __name__, template_folder='templates')

@product_api.route('/')
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    products = Product.query.order_by(Product.date_created.desc()).paginate(page=page, per_page=5)
    return render_template('products.html', products=products)

@product_api.route('/register', methods=['GET', 'POST'])
@login_required
def register():
    form = ProductRegisterForm()

    if form.validate_on_submit():
        product = Product(form.name.data, form.description.data)
        db.session.add(product)
        db.session.commit()
        flash('Product created with successs!', 'success')
        return redirect(url_for('product_api.home'))

    return render_template('registerproduct.html', title='Register Product', form = form)

productmanager/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from productmanager import db, bcrypt
from productmanager.forms import LoginForm
from productmanager.user.models import User
from flask_login import login_user, current_user, logout_user, login_required

home_api = Blueprint('home_api', __name__, template_folder='templates')

@home_api.route("/")
@login_required
def hello():
    return "Hello World!"

@home_api.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('product_api.home'))
    
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, True)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('product_api.home'))
        else:
            flash('Login Unsucessful. Please check email and password', 'danger')

    return render_template('login.html', title='Login', form = form)

@home_api.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('home_api.login'))

productmanager/user/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from productmanager import db, bcrypt
from productmanager.user.models import User
from productmanager.user.forms import UserRegisterForm, UserUpdateForm
from flask_login import current_user

user_api = Blueprint('user_api', __name__, template_folder='templates')

@user_api.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('product_api.home'))

    form = UserRegisterForm()

    if form.validate_on_submit():
        hash_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(form.email.data, form.name.data, hash_password)
        db.session.add(user)
        db.session.commit()
        flash('Account has been created with successs!', 'success')
        return redirect(url_for('home_api.login'))

    return render_template('register.html', title='Register Account', form = form)

@user_api.route('/update', methods=['GET', 'POST'])
def update():
    form = UserUpdateForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
    elif request.method == 'GET':
        form.name.data = current_user.name
        form.email.data = current_user.email

    return render_template('update.html', title='Update Account', form = form)

productmanager/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{{url_for('static', filename='materialcss/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='vendor.bundle.base.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='vendor.bundle.addons.css')}}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link rel="shortcut icon" href="../static/images/favicon.png" />

    {% if title %}
        <title>Product Manager - {{ title }}</title>
    {% else %}
        <title>Product Manager</title>
    {% endif %}
</head>
<body>
    
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
          <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
            <a class="navbar-brand brand-logo" href="index.html">
              <img src="images/logo.svg" alt="logo" />
            </a>
            <a class="navbar-brand brand-logo-mini" href="index.html">
              <img src="images/logo-mini.svg" alt="logo" />
            </a>
          </div>
          <div class="navbar-menu-wrapper d-flex align-items-center">
            
            <ul class="navbar-nav navbar-nav-right">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                  <span class="profile-text">Hello, {{current_user.name}} !</span>
                  <img class="img-xs rounded-circle" src="../static/images/faces/face1.jpg" alt="Profile image">
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
                  <a class="dropdown-item p-0">
                    <div class="d-flex border-bottom">
                      <div class="py-3 px-5 d-flex align-items-center justify-content-center border-left border-right">
                        <i class="mdi mdi-account-outline mr-0 text-gray"></i>
                      </div>
                      <div class="py-3 px-5 d-flex align-items-center justify-content-center">
                        <i class="mdi mdi-alarm-check mr-0 text-gray"></i>
                      </div>
                    </div>
                  </a>
                  <a href="{{url_for('user_api.update')}}" class="dropdown-item">
                    Manage Account
                  </a>
                  <a class="dropdown-item">
                    Change Password
                  </a>
                  <a href="{{url_for('home_api.logout')}}" class="dropdown-item">
                    Sign Out
                  </a>
                </div>
              </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
              <span class="icon-menu"></span>
            </button>
          </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
          <!-- partial:partials/_sidebar.html -->
          <nav class="sidebar sidebar-offcanvas" id="sidebar">
            <ul class="nav">
              <li class="nav-item nav-profile">
                <div class="nav-link">
                  <div class="user-wrapper">
                    <div class="profile-image">
                      <img src="../static/images/faces/face1.jpg" alt="profile image">
                    </div>
                    <div class="text-wrapper">
                      <p class="profile-name">Renan</p>
                      <div>
                        <small class="designation text-muted">Manager</small>
                        <span class="status-indicator online"></span>
                      </div>
                    </div>
                  </div>
                  <button class="btn btn-success btn-block" onclick="window.location.href='{{url_for('product_api.register')}}';">New Product
                    <i class="mdi mdi-plus"></i>
                  </button>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="index.html">
                  <i class="menu-icon mdi mdi-television"></i>
                  <span class="menu-title">Dashboard</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                  <i class="menu-icon mdi mdi-content-copy"></i>
                  <span class="menu-title">Basic UI Elements</span>
                  <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="ui-basic">
                  <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                      <a class="nav-link" href="pages/ui-features/buttons.html">Buttons</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="pages/ui-features/typography.html">Typography</a>
                    </li>
                  </ul>
                </div>
              </li>
            </ul>
          </nav>

          <div class="main-panel">
            <div class="content-wrapper">
              {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                  <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                        {{ message }}
                      </div>
                  {% endfor %}
                {% endif %}
              {% endwith %}
              {% block content %}{% endblock %}
            </div>

            <footer class="footer">
              <div class="container-fluid clearfix">
                <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2018
                  <a href="#">Renan Augusto</a>. All rights reserved.</span>
              </div>
            </footer>
          </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

productmanager/templates/externalbase.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{url_for('static', filename='materialcss/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='vendor.bundle.base.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='vendor.bundle.addons.css')}}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link rel="shortcut icon" href="../static/images/favicon.png" />

    {% if title %}
        <title>Product Manager - {{ title }}</title>
    {% else %}
        <title>Product Manager</title>
    {% endif %}
</head>

<body>
    {% block content %}{% endblock %}
  
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

productmanager/templates/login.html
{% extends "externalbase.html" %}
{% block content%}
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper auth-page">
        <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
            <div class="row w-100">
                <div class="col-lg-4 mx-auto">
                    <div class="auto-form-wrapper">
                        {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                                {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        {% endwith %}
                        <form method="POST">
                            {{ form.hidden_tag() }}
                            <div class="form-group">
                                {% if form.email.errors %}
                                    {{form.email(class="form-control is-invalid", placeholder="E-mail")}}
                                    <div class="invalid-feedback">
                                        {% for error in form.email.errors %}
                                            <span>{{error}}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{form.email(class="form-control",  placeholder="E-mail")}}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                    {% if form.password.errors %}
                                    {{form.password(class="form-control is-invalid", placeholder="Password")}}
                                    <div class="invalid-feedback">
                                        {% for error in form.password.errors %}
                                            <span>{{error}}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{form.password(class="form-control",  placeholder="Password")}}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary submit-btn btn-block">Login</button>
                            </div>
                            <div class="form-group d-flex justify-content-between">
                                <a href="#" class="text-small forgot-password text-black">Forgot Password</a>
                            </div>
                            <div class="text-block text-center my-3">
                                <span class="text-small font-weight-semibold">Not a member ?</span>
                                <a href="{{url_for('user_api.register')}}" class="text-black text-small">Create new account</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}